name: Laravel Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
        laravel: ['11.*', '12.*', '13.*']
        exclude:
          - php: '8.5'
            laravel: '11.*'
          - php: '8.2'
            laravel: '13.*'
        include:
          - laravel: '11.*'
            testbench: '9.*'
          - laravel: '12.*'
            testbench: '10.*'
          - laravel: '13.*'
            testbench: '11.*'

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('composer.json') }}

    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, pgsql, pdo_pgsql
        coverage: none

    - name: Install Dependencies
      run: |
        composer require "illuminate/support:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit --configuration phpunit.xml
